### ISSUE TITLE
算法助手没有reqable堆栈跟踪这个选项

### ISSUE THREAD

**Issue by ghost** [xmexg/xyks#49]
`算法助手`>`网络环境(屏蔽防抓包专题)`>没有`reqable堆栈跟踪`这个选项, 导致`webview`页面没法抓包, 请问这个问题应该怎么解决啊? 

![img](https://raw.githubusercontent.com/IGCrystal/IGCrystal.github.io/refs/heads/master/images/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202024-10-27%20221543.png)

**Comment by GalacticDevOps** [comment]
> `算法助手`>`网络环境(屏蔽防抓包专题)`>没有`reqable堆栈跟踪`这个选项, 导致`webview`页面没法抓包, 请问这个问题应该怎么解决啊?
> 
> ![img](https://raw.githubusercontent.com/IGCrystal/IGCrystal.github.io/refs/heads/master/images/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202024-10-27%20221543.png)

用算法助手Pro
